### ISSUE TITLE
Updated to Laravel 8 & Laravel 9

### ISSUE THREAD

**Issue by gokhanstar** [LaravelDaily/Laravel-Loan-Management-Demo#6]
Dear Mr. Povilas Korop, first of all thank you very much for your great work. I admire your work very much and try to develop my knowledge with your tutorials and sharings. I am a newbie for Laravel having a very old background from .NET and small projects from pure php/mysql. I had a big break from software development, but try to catch new technologies asap.

I updated your Loan-Management-Demo from Laravel 7 to Laravel 8 & then to Laravel 9 as you suggested in one of your tutorials again. Honestly it did not take much time. I mean, it should be a piece of cake for you, but if you need those updated versions I can share via google drive etc. or if you let me I can post on github, but I will need a guidance to do that. Again, from using github/composer/vs.code to creating web applications, everything is new for me. I am just trying to join and take a part in the community and give back as I take from you.

**Comment by PovilasKorop** [comment]
@gokhanstar thanks a lot for your offer. In reality, we would need to update many demos to the latest Laravel 10 version and not 8/9, but currently, we don't have it in our plans to update these old repositories, as we don't have a big demand of requests for it from our users/customers.

**Comment by gokhanstar** [comment]
Thank you for your prompt response and warm approach. I will keep following your works. I hope some day, I can have a part on your projects also. Best regards.
